#!/usr/bin/env sh
set -- \
    "cargo fmt -- --check" \
    "cargo make clippy"

for workdir in $(git ls-tree -r --name-only HEAD | grep Cargo.lock | parallel 'dirname {}' | parallel 'readlink -f')
do
    parallel --bar -t --halt now,fail=1 --workdir "$workdir" '{}' ::: "$@"
done
