#!/usr/bin/env sh
PC_RUST_MANIFEST_DIRS=$(git ls-tree -r --name-only HEAD | grep Cargo.toml | parallel 'dirname {}')

set -- \
    "cargo fmt -- --check" # \
    # "cargo clippy --all-targets -- -D warnings" \
    # "cargo test"

if [ -n "$PC_RUST_MANIFEST_DIRS" ]
then
    for cmd in "$@"
    do
        echo "$cmd"
        parallel "(cd {} && $cmd)" ::: "$PC_RUST_MANIFEST_DIRS"
    done
fi
