#!/usr/bin/env sh

# cgrep: chained `grep`
# source: https://unix.stackexchange.com/a/326270
cgrep()
{
    local pattern="$1"
    if [[ -z "$pattern" ]]
    then
        cat
        return
    fi
    shift
    grep -- "$pattern" | cgrep "$@"
}

# clipv: `xclip` copy to clipboard
clipc()
{
    xclip -selection clipboard -in
}

# clipv: `xclip` paste from clipboard
clipv()
{
    xclip -selection clipboard -out
}

# terr: `tee` stdout to stderr
terr()
{
    tee >(cat 1>&2)
}
