name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install make
      run: sudo apt-get update -y && sudo apt-get install -y make

    - name: Run make
      run: make
      
    - name: Run check
      run: make check
